const app=document.getElementById("app");
const parents={"main-photo":"home","poster-printer":"home","ipos":"home","main-products":"main-photo","main-supplies":"main-photo","main-maintenance":"main-photo","main-troubleshooting":"main-photo","poster-supplies":"poster-printer","support-main":"main-photo","support-poster":"poster-printer","support-ipos":"ipos","guide-canvas":"main-products","guide-photo-books":"main-products","guide-calendars":"main-products","guide-magnets":"main-products","guide-drinkware":"main-products","guide-specialty":"main-products","guide-poster-products":"poster-printer","guide-load-paper":"poster-printer","guide-replace-ink":"poster-printer","guide-poster-troubleshooting":"poster-printer","guide-photo-checkout":"ipos","guide-qr-pickup":"ipos","guide-register-troubleshooting":"ipos","guide-customer-questions":"ipos"};
function routeTo(id,push=true){const t=id||"home";render(t);if(push)history.pushState({page:t},"",`#${t}`);scrollTo({top:0,behavior:"smooth"})}
function pageTitle(id){if(id==="home")return PE_DATA.home.title;if(PE_DATA.pages[id])return PE_DATA.pages[id].title;if(PE_DATA.supplies[id])return PE_DATA.supplies[id].title;if(PE_DATA.masterGuides?.[id])return PE_DATA.masterGuides[id].title;return PE_DATA.guides[id]||"Page Not Found"}
function heading(title,description,id){const label=id==="home"?"Choose a workstation":PE_DATA.pages[id]?"Workstation support":PE_DATA.supplies[id]?"Supply reference":PE_DATA.masterGuides?.[id]?"Master training guide":"Quick guide";return `<section class="page-heading ${id==="home"?"home-heading":""}"><p class="eyebrow">${label}</p><h2>${title}</h2><p class="page-description">${description||""}</p>${id==="home"?'<div class="hero-chips"><span>QR-ready</span><span>Mobile-first</span><span>Fast task support</span></div>':""}</section>`}
function header(){return `<header class="site-header"><div class="brand-row"><button class="brand-lockup" type="button" onclick="routeTo('home')"><span class="cvs-brand"><span class="heart-text">♥</span><span class="cvs-word">CVS</span></span><span class="brand-divider"></span><span class="project-name"><strong>Project Excellence</strong><small>Operational Excellence. Every Time.</small></span></button><div class="header-tools"><span class="department-pill">CVS PHOTO</span><span class="version-pill">v${PE_DATA.version}</span></div></div><div class="red-rule"></div><div class="context-row"><div class="context-inner"><span class="context-label">Operational Knowledge System</span><span class="context-status"><span></span> New-hire quick support</span></div></div></header>`}
function footer(){return `<footer class="site-footer"><div class="footer-inner"><div class="footer-brand"><span class="heart-text">♥</span><span>Project Excellence</span></div><p>CVS Photo operational support</p><span class="footer-version">Version ${PE_DATA.version}</span></div></footer>`}
function back(id){return id==="home"?"":`<button class="back-btn" type="button" onclick="routeTo('${parents[id]||"home"}')">← Back</button>`}
function render(id="home"){document.title=`${pageTitle(id)} | Project Excellence`;app.innerHTML=`<div class="app-shell"><a class="skip-link" href="#main-content">Skip to content</a>${header()}<main class="container" id="main-content">${back(id)}${content(id)}</main>${footer()}</div>`}
function label(id){return["main-photo","poster-printer","ipos"].includes(id)?"WORKSTATION":id.startsWith("support-")?"ESCALATION":id.includes("supplies")?"REFERENCE":"GUIDE"}
function cards(items){return `<div class="card-grid">${items.map(x=>`<button class="card" type="button" onclick="routeTo('${x.id}')"><span class="card-meta">${label(x.id)}</span><span class="card-icon" aria-hidden="true">${x.icon}</span><span class="card-title">${x.title}</span><span class="card-desc">${x.description}</span><span class="card-action">Open →</span></button>`).join("")}</div>`}
function content(id){if(id==="home")return heading(PE_DATA.home.title,PE_DATA.home.description,id)+cards(PE_DATA.home.cards);if(PE_DATA.pages[id])return heading(PE_DATA.pages[id].title,PE_DATA.pages[id].description,id)+cards(PE_DATA.pages[id].cards);if(PE_DATA.supplies[id])return supplies(id);if(PE_DATA.masterGuides?.[id])return master(id,PE_DATA.masterGuides[id]);if(PE_DATA.guides[id])return guide(id,PE_DATA.guides[id]);return heading("Page Not Found","Return home and choose a workstation.",id)+cards(PE_DATA.home.cards)}
function supplies(id){const d=PE_DATA.supplies[id];return `${heading(d.title,d.description,id)}<section class="search-panel"><div class="search-icon">⌕</div><div class="search-copy"><strong>Find a supply</strong><span>Search by name, item number, category, or note.</span></div><label class="sr-only" for="supplySearch">Search supplies</label><input class="search" id="supplySearch" type="search" placeholder="Search supplies..." oninput="filterTable()"></section><div class="table-wrap"><table id="supplyTable"><thead><tr><th>Category</th><th>Item</th><th>CVS Item #</th><th>Notes</th></tr></thead><tbody>${d.rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function master(id,g){const q=g.quickSteps.map(s=>`<li class="quick-step"><span class="quick-step-number">${s[0]}</span><div><strong>${s[1]}</strong><p>${s[2]}</p></div></li>`).join("");const steps=g.procedureSteps.map(s=>`<li class="master-procedure-card"><span class="procedure-number">${s[0]}</span><div class="procedure-card-copy"><h4>${s[1]}</h4><p>${s[2]}</p></div></li>`).join("");return `${heading(g.title,g.description,id)}<article class="master-guide"><section class="master-overview"><div class="master-status-row"><span class="master-badge">MASTER TEMPLATE</span><span class="status-pill">${g.status}</span></div><div class="master-meta"><span><strong>Time</strong>${g.time}</span><span><strong>Skill level</strong>${g.skill}</span><span><strong>Goal</strong>Load correctly the first time</span></div><div class="start-here"><div class="start-here-heading"><span>START HERE</span><h3>Six actions to remember</h3><p>Use the full workflow below when you need more detail.</p></div><ol class="quick-steps">${q}</ol></div><div class="master-caution"><span>!</span><p><strong>Never force the equipment.</strong> ${g.escalation}</p></div></section><section class="master-procedure"><div class="master-procedure-heading"><div><p class="eyebrow">Step-by-step procedure</p><h3>Follow the numbered workflow</h3></div><span class="procedure-count">${g.procedureSteps.length} steps</span></div><ol class="master-procedure-grid">${steps}</ol></section><section class="master-checks"><div><p class="eyebrow">Before resuming output</p><h3>Quick quality check</h3><ul>${g.checks.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="leadership-note"><p class="eyebrow">Training standard</p><h3>Keep it fast and consistent</h3><p>Store leadership should verify approved media settings and local escalation steps before final rollout.</p></div></section></article>`}
function guide(id,title){if(id.startsWith("support-"))return support(id);return `${heading(title,"Use this guide for quick, point-of-need support. Final steps and visuals will be added after review.",id)}<article class="guide"><div class="guide-banner"><div class="guide-banner-icon">${PE_DATA.guideIcons?.[id]||"✓"}</div><div><span>PROJECT EXCELLENCE GUIDE</span><strong>${title}</strong></div></div><div class="info-grid"><div class="info-box"><div class="info-label">Status</div><span class="status-pill">Template Ready</span></div><div class="info-box"><div class="info-label">Version</div><strong>${PE_DATA.version} Draft</strong></div><div class="info-box"><div class="info-label">Owner</div><strong>Project Excellence</strong></div></div><section class="guide-section"><span class="section-number">01</span><div><h3>Purpose</h3><p>Complete the task accurately and consistently.</p></div></section><section class="guide-section"><span class="section-number">02</span><div><h3>Quick Workflow</h3><ol><li>Confirm the order.</li><li>Gather the correct supplies.</li><li>Complete the approved process.</li><li>Check quality.</li></ol></div></section></article>`}
function support(id){return `${heading("Support Contacts","Use this section when a task cannot be completed using the guide.",id)}<article class="guide"><div class="guide-banner dark"><div class="guide-banner-icon">☎</div><div><span>ESCALATION SUPPORT</span><strong>Get the right help quickly</strong></div></div><div class="support-grid"><section><h3>Store Support</h3><ul><li><span>Store Manager</span><strong>________________</strong></li><li><span>Shift Supervisor</span><strong>________________</strong></li><li><span>Photo-trained colleague</span><strong>________________</strong></li></ul></section><section><h3>Technical Support</h3><ul><li><span>Photo Help Desk</span><strong>________________</strong></li><li><span>Register Support</span><strong>________________</strong></li></ul></section></div></article>`}
function filterTable(){const i=document.getElementById("supplySearch"),t=document.getElementById("supplyTable");if(!i||!t)return;const q=i.value.trim().toLowerCase();[...t.querySelectorAll("tbody tr")].forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q)?"":"none")}
addEventListener("popstate",()=>render(location.hash.replace("#","")||"home"));addEventListener("load",()=>render(location.hash.replace("#","")||"home"));
